# Generated by Django 6.1 on 2026-08-16 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('preparation', 'preparation'), ('started', 'started'), ('construction', 'construction'), ('initial-delivery', 'initial-delivery'), ('final-delivery', 'final-delivery')], default='preparation', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('started_date', models.DateField()),
                ('initial_delivery', models.DateField()),
                ('final_delivery', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='constructing.contacts')),
            ],
        ),
    ]
